DAP-1070: LAN instructions page
bcgov/citz-grs-dats pull request #407
Opened 2024-12-30 22:37 UTC by BradyMitch

## 🎯 Summary

  
[DAP-1070](https://citz-cirmo.atlassian.net/browse/DAP-1070)

## 🔰 Checklist

- [x] I have read and agree with the following checklist.

> - I have performed a self-review of my code.
> - I have commented my code, particularly in hard-to-understand areas.
> - I have made corresponding changes to the documentation where required.
> - I have tested my changes to the best of my ability.
> - I have consulted with the team if introducing a new dependency.
> - My changes generate no new warnings.

2025-01-06 17:41 UTC, TaylorFries requested changes
adding a review before the pr is fully out of draft. 
apologies if the changes listed were already planned.

2025-01-06 17:41 UTC, TaylorFries commented on desktop/src/renderer/src/pages/SendRecords.tsx
> +					border: "1px solid #053662",
color variables for #FAF9F8, #474543, #F7F9FC, #053662

2025-01-06 17:41 UTC, TaylorFries commented on desktop/src/renderer/src/pages/transfers/LanInstructions.tsx
> +		</Stack>
maybe make a note component?

2025-01-08 18:40 UTC, TaylorFries approved these changes

2025-01-09 17:06 UTC, TaylorFries approved these changes

2025-01-09 17:27 UTC, BradyMitch commented on desktop/src/renderer/src/pages/index.ts
> +export * from "./transfers";
```suggestion
export * from "./transfers";

```

2025-01-09 17:28 UTC, TaylorFries approved these changes

2025-01-09 17:28 UTC, merged