Side nav updates
bcgov/citz-grs-dats pull request #408
Opened 2024-12-30 23:10 UTC by BradyMitch

## 🎯 Summary

  

No addition of help menu but other styles updated to match designs

## 🔰 Checklist

- [x] I have read and agree with the following checklist.

> - I have performed a self-review of my code.
> - I have commented my code, particularly in hard-to-understand areas.
> - I have made corresponding changes to the documentation where required.
> - I have tested my changes to the best of my ability.
> - I have consulted with the team if introducing a new dependency.
> - My changes generate no new warnings.

2025-01-06 17:11 UTC, TaylorFries requested changes
Adding these comments as a prereview before the pr is no longer a draft. 
apologies if these were things that would be updated.

2025-01-06 17:11 UTC, TaylorFries commented on desktop/src/renderer/src/components/SideNav.tsx
> +									icon={<SendRecordsIcon sx={{ color: "#474543" }} />}
color variable :D

2025-01-07 17:19 UTC, BradyMitch commented on desktop/src/renderer/src/components/SideNav.tsx
> +					<List sx={{ display: "flex", flexDirection: "column", gap: 1 }}>
In the design the header and that bar arent actually aligned so I dont know if its a big deal. If we are to adjust this I think it would be better to keep the gap and adjust the margin on the home button

2025-01-09 17:45 UTC, BradyMitch commented on desktop/src/renderer/src/components/SideNav.tsx
> +						width: "100%",
if its not there the size of the nav bar is wack

2025-01-09 23:38 UTC, TaylorFries approved these changes

2025-01-09 23:40 UTC, merged